### ISSUE TITLE
Request a new color scheme for the site 

### ISSUE THREAD

**Issue by CandyZQ** [CSbyUs/csbyus-on-rails#21]
As @vivkirb mentioned, our site looks like a big google form right now. I think one of the reason is that we are using too many colors on our website. For example, the topAppBar is a mix of purple and blue, the youtube video overview on our homepage is cyan, yet the contact form is in light green. 

 I think it can be nice if we could have a new color scheme before Feb 1st. It should be an easy code change, but would make the site look more unified! What are your opinions @vivkirb @jestradasal ?

**Comment by vivkirb** [comment]
yes!! I definitely agree. personally I think some sort of light blue/teal would be one good color to incorporate (like the lightish blue in the beginning of the youtube video that's on the homepage), because blue is universally liked and also just works with the whole concept of tech, but that's just my opinion!

**Comment by tannerljohnson** [comment]
absolutely! i love the idea of using blue @vivkirb -- looks super clean and approachable. I also love the color scheme CRD used for the Mobile Citizens overview. Check it out on [page 2 of this link] (https://docs.google.com/document/d/14HhURHo2u9WwidZ83Px70qQ8U8411ClAh--IZ4Oxz20/edit?usp=sharing). Would love to know your thoughts and/or see mock-ups you experiment with @vivkirb @jestradasal @CandyZQ 👍
