### ISSUE TITLE
Users_Controller_Test not passing 

### ISSUE THREAD

**Issue by CandyZQ** [CSbyUs/csbyus-on-rails#74]

**Comment by tannerljohnson** [comment]
I think this is due to the format of the test
You create the test user object by referencing the first user in the database 
```
  setup do
    @user = users(:one)
  end
```
The test that fails is this:
```
Failure:
UsersControllerTest#test_should_create_user [/Users/tannerjohnson/Documents/csbyus/dev/csbyus-on-rails/test/controllers/users_controller_test.rb:19]:
"User.count" didn't change by 1.
Expected: 4
  Actual: 3
```
Since your controller forces non-repeat emails, it's logical that this test would fail. Consider creating a fresh user object for this test @CandyZQ

**Comment by CandyZQ** [comment]
#80
